// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

using System;

namespace _2
{
    class Program
    {
        static void Main()
        {
            long current = 1;
            long prev = 1;
            long temp;
            long sum = 0;
            while (current<4000000)
            {
                Console.WriteLine(current);
                if(current%2==0)
                { 
                    sum += current;
                }
                temp = current;
                current = current + prev;
                prev = temp;   
            }
            Console.WriteLine("sum=" + sum);
        }
    }
}

